const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx=vm.createContext({});
vm.runInContext(fs.readFileSync('web/static/electrs_status.js','utf8')+';globalThis.rows=ElectrsStatus.rows;globalThis.progress=ElectrsStatus.progress;',ctx);
let rows=ctx.rows({state:'INDEXING',height:1234,height_updated:100,height_stale:false,rpc_error:'Electrum response delayed'},102);
assert.equal(rows[1][1],'인덱싱 중');assert.equal(rows[0][1],'1,234');assert.equal(rows[2][1],'2초 전');assert.equal(rows[3][1],'응답 지연 · 자동 재확인');
rows=ctx.rows({state:'STALE',height:1234,height_updated:100,height_stale:true},108);
assert.equal(rows[0][1],'1,234');assert.equal(rows[2][1],'마지막 확인 · 8초 전');assert.notEqual(rows[3][1],'준비 완료');
rows=ctx.rows({state:'READY',height:42,height_updated:100,rpc_updated:100,wallet_ready:true},102);
assert.equal(rows[3][1],'준비 완료');
assert.equal(ctx.rows({state:'STARTING'},102)[0][1],'—');
assert.equal(ctx.rows({state:'READY',height:42,height_updated:100},120)[2][1],'마지막 확인 · 20초 전');
assert.equal(ctx.progress({height:99,target_height:100}).percent,99);
assert.equal(ctx.progress({height:999999,target_height:1000000}).percent,99.99);
assert.equal(ctx.progress({height:100,target_height:100,state:'VERIFYING'}).state,'인덱스·지갑 응답 확인 중');
assert.equal(ctx.progress({height:0,target_height:0}).percent,100);
assert.equal(ctx.progress({height:42}).percent,null);
const index=fs.readFileSync('web/static/index.html','utf8');assert(index.indexOf('/electrs_status.js')<index.indexOf('/dashboard.js'));
assert(fs.readFileSync('web/server.py','utf8').includes("'electrs_status.js'"));
console.log('PASS: progress, stale height/timestamp, wallet readiness, initial state and static asset routing');
